[0m15:48:38.049978 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000110107DF950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011010707200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000110107DE000>]}


============================== 15:48:38.078270 | 8ad80217-0d01-439d-9cfa-5b671d76927d ==============================
[0m15:48:38.078270 [info ] [MainThread]: Running with dbt=1.7.19
[0m15:48:38.081057 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\pujad\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:49:07.557675 [debug] [MainThread]: Starter project path: C:\Users\pujad\OneDrive - APS Consult\Bureau\DBT_demo\.venv\Lib\site-packages\dbt\include\starter_project
[0m15:49:07.582784 [info ] [MainThread]: 
Your new dbt project "DBT_Projet" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:49:07.584291 [info ] [MainThread]: Setting up your profile.
[0m15:49:15.588556 [debug] [MainThread]: Command `dbt init` succeeded at 15:49:15.588556 after 37.74 seconds
[0m15:49:15.589999 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000110106639B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011010707200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001101062AF30>]}
[0m15:49:15.590503 [debug] [MainThread]: Flushing usage events
[0m17:04:27.352745 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E96156780>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E96156150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E96155DF0>]}


============================== 17:04:27.361316 | 8328e8f8-94be-4db1-84ae-c12d16a4dddc ==============================
[0m17:04:27.361316 [info ] [MainThread]: Running with dbt=1.7.19
[0m17:04:27.362988 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\pujad\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m17:04:27.362988 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\pujad\OneDrive - APS Consult\Bureau\DBT_demo\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:04:27.363995 [debug] [MainThread]: Command `dbt run` failed at 17:04:27.363995 after 0.20 seconds
[0m17:04:27.365164 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E9607A780>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E95FEAAE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E96155730>]}
[0m17:04:27.365164 [debug] [MainThread]: Flushing usage events
[0m17:10:42.955278 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017999EE7B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017999EE79E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017999EE7830>]}


============================== 17:10:42.963854 | 82ae0fb3-29fb-4a27-a10d-8bccf090b2e8 ==============================
[0m17:10:42.963854 [info ] [MainThread]: Running with dbt=1.7.19
[0m17:10:42.964854 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\pujad\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:10:42.964854 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\pujad\OneDrive - APS Consult\Bureau\DBT_demo\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:10:42.967492 [debug] [MainThread]: Command `dbt run` failed at 17:10:42.966423 after 0.23 seconds
[0m17:10:42.967492 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017999EE55E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017999EE6A80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017999EE7260>]}
[0m17:10:42.968492 [debug] [MainThread]: Flushing usage events
[0m17:12:00.060781 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000274786ED5E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000274786EC200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000274786ED550>]}


============================== 17:12:00.067780 | 885b0213-2f97-43bf-ae96-8efc7f17efeb ==============================
[0m17:12:00.067780 [info ] [MainThread]: Running with dbt=1.7.19
[0m17:12:00.068723 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\pujad\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run --select stg_customers', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:12:00.069235 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\pujad\OneDrive - APS Consult\Bureau\DBT_demo\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:12:00.071302 [debug] [MainThread]: Command `dbt run` failed at 17:12:00.069235 after 0.20 seconds
[0m17:12:00.071302 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000274786EF8C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000274786EFD10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000274786ED4C0>]}
[0m17:12:00.072298 [debug] [MainThread]: Flushing usage events
